/*

 DINOSAURIO.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Dinosaurio[] =
{
  0x0F,0x0F,0x0B,0x0B,0x0F,0x0F,0xFC,0xFC,
  0x78,0x78,0x70,0x70,0x10,0x10,0x00,0x00,
  0x0F,0x0F,0x0B,0x0B,0x0F,0x0F,0xFC,0xFC,
  0x78,0x78,0x70,0x70,0x40,0x40,0x00,0x00
};

/* End of DINOSAURIO.C */
